apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysql-backup
  namespace: mysql
  labels:
    app: mysql-backup
    environment: "prod"
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          volumes:
          - name: mysql-backup
            persistentVolumeClaim:
              claimName: mysql-backup-claim
          # dnsPolicy: "None"
          # dnsConfig:
          #   nameservers:
          #     - 8.8.8.8
          #     - 8.8.4.4
          restartPolicy: Never
          containers:
          - name:  mysql-backup
            imagePullPolicy: Always
            image: 10.0.0.242:5000/mysql-backup:latest
            envFrom:
              - configMapRef:
                  name: mysql-backup
            volumeMounts:
              - name: mysql-backup
                mountPath: /root/pg-backup
