apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-backup-claim
  namespace: mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2G
  storageClassName: nfs-client